# Generated by Django 4.2.11 on 2026-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Store name', max_length=255)),
                ('location', models.CharField(help_text='Store location/address', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='stores_stor_name_988b60_idx')],
            },
        ),
    ]
